Выполнила Леопаева Л.А., 6402-010302D

Лабораторная работа 2

In [1]:
import numpy as np
from itertools import combinations

In [2]:
# Начальные данные
matrix_x1 = np.array([[1, 1, 1],
                      [1, 1, 0],
                      [1, 0, 1],
                      [0, 1, 1]])

matrix_x2 = np.array([[0, 1, 1, 1, 1, 0, 0],
                      [1, 1, 0, 1, 1, 1, 1],
                      [0, 0, 1, 1, 0, 1, 1],
                      [1, 0, 1, 0, 1, 1, 0]])


Часть 1

2.1. Сформировать порождающую матрицу линейного кода (7, 4, 3)

In [3]:
def generate_G(x, k):
    identity_k = np.eye(k, dtype=int)
    return np.hstack((identity_k, x))

2.2 Сформировать проверочную матрицу на основе порождающей

In [4]:
def generate_H(x, n, k):
    identity_remainder = np.eye(n - k, dtype=int)
    return np.vstack((x, identity_remainder))

2.3 Сформировать таблицу синдромов для всех однократных
ошибок

In [5]:
def syndromes_single_error(H):
    syndromes = {}
    for index, row in enumerate(H):
        syndromes[str(row)] = [index]
    return syndromes

2.4 Исправить одну ошибку с использованием таблицы синдромов

In [6]:
def fix_one_error(syndromes, syndrome, word):
    position = syndromes.get(str(syndrome))
    if position is not None:
        word[position] ^= 1
    return word

Сформировать кодовое слово длины n из слова длины k. Внести однократную
(двукратную) ошибку в сформированное слово. Вычислить синдром,
исправить ошибку с использованием таблицы синдромов. Убедиться
в правильности полученного слова. (Убедиться, что полученное 
слово отличается от отправленного.)

In [25]:
def part_one():
    print("\nЧасть 1")
    n, k = 7, 4
    G = generate_G(matrix_x1, k)
    print(f"Порождающая матрица G:\n{G}")
    H = generate_H(matrix_x1, n, k)
    print(f"Проверочная матрица H:\n{H}")

    syndromes = syndromes_single_error(H)
    print(f"Таблица синдромов для однократных ошибок:\n{syndromes}")

    # 2.4
    print("\n\nПункт 2.4: слово с одной ошибкой")
    original_word = np.array([1, 0, 1, 0])
    encoded_word = original_word @ G % 2
    print(f"\nИсходное слово: {original_word}")
    print(f"Закодированное слово: {encoded_word}")

    error_word = encoded_word.copy()
    error_word[5] ^= 1  # Добавляем одну ошибку
    syndrome = error_word @ H % 2
    print(f"Слово с ошибкой: {error_word}\nСиндром: {syndrome}")

    corrected_word = fix_one_error(syndromes, syndrome, error_word)
    print(f"Исправленное слово: {corrected_word}")
    
    is_correct = corrected_word @ H % 2
    print(f"Проверка правильности полученного слова умножением на матрицу H: {is_correct}")
    
    # 2.5
    print("\n\nПункт 2.5: слово с двумя ошибками")
    original_word_2 = np.array([0, 1, 0, 1])
    encoded_word_2 = original_word_2 @ G % 2
    print(f"\nИсходное слово: {original_word_2}")
    print(f"Закодированное слово: {encoded_word_2}")

    error_word_2 = encoded_word_2.copy()
    error_word_2[[2, 5]] ^= 1  # Добавляем две ошибки
    syndrome_2 = error_word_2 @ H % 2
    print(f"Слово с двумя ошибками: {error_word_2}\nСиндром: {syndrome_2}")

    corrected_word_2 = fix_one_error(syndromes, syndrome_2, error_word_2)
    print(f"Исправленное слово: {corrected_word_2}")
    
    is_correct_2 = corrected_word_2 @ H % 2
    print(f"Проверка правильности полученного слова умножением на матрицу H: {is_correct_2}")
    
    print(f"Полученное слово отличается от отправленного: {encoded_word_2} -> {corrected_word_2}")

In [26]:
part_one()


Часть 1
Порождающая матрица G:
[[1 0 0 0 1 1 1]
 [0 1 0 0 1 1 0]
 [0 0 1 0 1 0 1]
 [0 0 0 1 0 1 1]]
Проверочная матрица H:
[[1 1 1]
 [1 1 0]
 [1 0 1]
 [0 1 1]
 [1 0 0]
 [0 1 0]
 [0 0 1]]
Таблица синдромов для однократных ошибок:
{'[1 1 1]': [0], '[1 1 0]': [1], '[1 0 1]': [2], '[0 1 1]': [3], '[1 0 0]': [4], '[0 1 0]': [5], '[0 0 1]': [6]}


Пункт 2.4: слово с одной ошибкой

Исходное слово: [1 0 1 0]
Закодированное слово: [1 0 1 0 0 1 0]
Слово с ошибкой: [1 0 1 0 0 0 0]
Синдром: [0 1 0]
Исправленное слово: [1 0 1 0 0 1 0]
Проверка правильности полученного слова умножением на матрицу H: [0 0 0]


Пункт 2.5: слово с двумя ошибками

Исходное слово: [0 1 0 1]
Закодированное слово: [0 1 0 1 1 0 1]
Слово с двумя ошибками: [0 1 1 1 1 1 1]
Синдром: [1 1 1]
Исправленное слово: [1 1 1 1 1 1 1]
Проверка правильности полученного слова умножением на матрицу H: [0 0 0]
Полученное слово отличается от отправленного: [0 1 0 1 1 0 1] -> [1 1 1 1 1 1 1]


Часть 2

In [27]:
def syndromes_double_error(H, n):
    syndromes = {}
    identity_n = np.eye(n, dtype=int)
    for idx, row in enumerate(H):
        syndromes[str(row)] = [idx]
    for pair in combinations(range(n), 2):
        error_pattern = (identity_n[pair[0]] + identity_n[pair[1]]) % 2
        syndrome = error_pattern @ H % 2
        syndromes[str(syndrome)] = pair
    return syndromes

In [28]:
def fix_two_errors(syndromes, syndrome, word):
    error_positions = syndromes.get(str(syndrome), [])
    for pos in error_positions:
        word[pos] ^= 1
    return word

Сформировать кодовое слово длины n из слова длины k. Внести
однократную (двукратную/трёхкратную) ошибку в сформированное слово. Вычислить синдром,
исправить ошибку с использованием таблицы синдромов. Убедиться
в правильности полученного слова (/Убедиться, что полученное слово отличается от отправленного).

In [35]:
def part_two():
    print("\nЧасть 2")
    # 2.6. Сформировать порождающую матрицу линейного кода (n, k, 5)
    n, k = 11, 4
    G = generate_G(matrix_x2, k)
    print(f"Порождающая матрица G:\n{G}")
    # 2.7 Сформировать проверочную матрицу на основе порождающей
    H = generate_H(matrix_x2, n, k)
    print(f"Проверочная матрица H:\n{H}")

    # 2.8 Сформировать таблицу синдромов для всех однократных и двукратных ошибок
    syndromes = syndromes_double_error(H, n)
    print(f"Таблица синдромов для однократных и двукратных ошибок:\n{syndromes}")

    # 2.9
    print("\n\nПункт 2.9: слово с одной ошибкой")
    original_word = np.array([1, 0, 1, 0])
    encoded_word = original_word @ G % 2
    print(f"\nИсходное слово: {original_word}")
    print(f"Закодированное слово: {encoded_word}")

    error_word = encoded_word.copy()
    error_word[5] ^= 1  # Добавляем одну ошибку
    syndrome = error_word @ H % 2
    print(f"Слово с ошибками: {error_word}\nСиндром: {syndrome}")

    corrected_word = fix_two_errors(syndromes, syndrome, error_word)
    print(f"Исправленное слово: {corrected_word}")
    
    # 2.10
    print("\n\nПункт 2.10: слово с двумя ошибками")
    original_word = np.array([1, 0, 0, 1])
    encoded_word = original_word @ G % 2
    print(f"\nИсходное слово: {original_word}")
    print(f"Закодированное слово: {encoded_word}")

    error_word = encoded_word.copy()
    error_word[[2, 5]] ^= 1  # Добавляем две ошибки
    syndrome = error_word @ H % 2
    print(f"Слово с ошибками: {error_word}\nСиндром: {syndrome}")

    corrected_word = fix_two_errors(syndromes, syndrome, error_word)
    print(f"Исправленное слово: {corrected_word}")
    
    # 2.11
    print("\n\nПункт 2.11: слово с тремя ошибками")
    original_word = np.array([1, 1, 1, 0])
    encoded_word = original_word @ G % 2
    print(f"\nИсходное слово: {original_word}")
    print(f"Закодированное слово: {encoded_word}")

    error_word = encoded_word.copy()
    error_word[[2, 5, 8]] ^= 1  # Добавляем две ошибки
    syndrome = error_word @ H % 2
    print(f"Слово с ошибками: {error_word}\nСиндром: {syndrome}")

    corrected_word = fix_two_errors(syndromes, syndrome, error_word)
    print(f"Исправленное слово: {corrected_word}")
    
    print(f"Полученное слово отличается от отправленного: {encoded_word} -> {corrected_word}")

In [36]:
part_two()


Часть 2
Порождающая матрица G:
[[1 0 0 0 0 1 1 1 1 0 0]
 [0 1 0 0 1 1 0 1 1 1 1]
 [0 0 1 0 0 0 1 1 0 1 1]
 [0 0 0 1 1 0 1 0 1 1 0]]
Проверочная матрица H:
[[0 1 1 1 1 0 0]
 [1 1 0 1 1 1 1]
 [0 0 1 1 0 1 1]
 [1 0 1 0 1 1 0]
 [1 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1]]
Таблица синдромов для однократных и двукратных ошибок:
{'[0 1 1 1 1 0 0]': [0], '[1 1 0 1 1 1 1]': [1], '[0 0 1 1 0 1 1]': [2], '[1 0 1 0 1 1 0]': [3], '[1 0 0 0 0 0 0]': [4], '[0 1 0 0 0 0 0]': [5], '[0 0 1 0 0 0 0]': [6], '[0 0 0 1 0 0 0]': [7], '[0 0 0 0 1 0 0]': [8], '[0 0 0 0 0 1 0]': [9], '[0 0 0 0 0 0 1]': [10], '[1 0 1 0 0 1 1]': (0, 1), '[0 1 0 0 1 1 1]': (0, 2), '[1 1 0 1 0 1 0]': (0, 3), '[1 1 1 1 1 0 0]': (0, 4), '[0 0 1 1 1 0 0]': (0, 5), '[0 1 0 1 1 0 0]': (0, 6), '[0 1 1 0 1 0 0]': (0, 7), '[0 1 1 1 0 0 0]': (0, 8), '[0 1 1 1 1 1 0]': (0, 9), '[0 1 1 1 1 0 1]': (0, 10), '[1 1 1 0 1 0 0]': (1, 2), '[0 1 1 1 0 0 1]': (1, 3), '[0 1 0 1 