Выполнила Леопаева Л.А., 6402-010302D

Лабораторная работа 3

In [22]:
import random
import numpy as np

In [23]:
def correct_error(syndrome_table, syndrome, word):
    indices = syndrome_table.get(str(syndrome))
    if indices is None:
        print("Синдром отсутствует в таблице синдромов.")
    else:
        word[indices] = (word[indices] + 1) % 2
    return word

3.1 Функция формирования порождающей и проверочной
матриц кода Хэмминга 

In [24]:
def create_syndrome_table(H):
    syndrome_table = {}
    for i in range(len(H)):
        syndrome_table[str(H[i])] = [i]
    return syndrome_table

In [25]:
def generate_hamming_matrices(r):
    t = np.array([[int(bit) for bit in format(i, f'0{r}b')] for i in range(2 ** r)])
    valid_rows = [i for i, row in enumerate(t) if sum(row) <= 1]
    t = np.delete(t, valid_rows, axis=0)
    t = np.flip(t, axis=0)  # Переворачиваем матрицу
    G = np.hstack((np.eye(len(t), dtype=int), t))  # Порождающая матрица
    H = np.vstack((t, np.eye(r, dtype=int)))  # Проверочная матрица
    return G, H

3.2. Исследование кода Хэмминга для одно-, двух- и трёхкратных ошибок 

In [26]:
def check_errors_in_hamming_code(G, H, syndrome_table, r, extended=False):
    e = np.eye(G.shape[1], dtype=int)
    x = np.random.randint(0, 2, 2**r - r - 1)
    encoded_word = x @ G % 2
    num_errors = 5 if extended else 4

    for step in range(1, num_errors):
        print("\nИсходное слово: ", x)
        print("Отправленное слово: ", encoded_word)
        indices_with_errors = random.sample(range(0, e.shape[0]), step)
        word_with_errors = encoded_word.copy()
        
        for i in indices_with_errors:
            word_with_errors = (word_with_errors + e[i]) % 2
        
        print(f"Слово с {step} ошибками: ", word_with_errors)
        syndrome = word_with_errors @ H % 2
        print("Синдром: ", syndrome)

        corrected_word = correct_error(syndrome_table, syndrome, word_with_errors)
        print("Исправленное слово: ", corrected_word)
        
        # Проверка исправленного слова
        validation = corrected_word @ H % 2
        print(f"Проверка исправленного слова с использованием матрицы H: ", validation, '\n')


In [27]:
def standard_hamming_code():
    print("\n\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>", "Для стандартного кода Хэмминга", "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<")
    for r in range(2, 5):
        print("\n\n                                    Параметр r = ", r, '\n')
        G, H = generate_hamming_matrices(r)
        syndrome_table = create_syndrome_table(H)
        print("Порождающая матрица G:", G, sep='\n')
        print("Проверочная матрица H:", H, sep='\n')
        print("Таблица синдромов: ", syndrome_table)
        check_errors_in_hamming_code(G, H, syndrome_table, r, extended=False)

In [28]:
standard_hamming_code()



>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Для стандартного кода Хэмминга <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


                                    Параметр r =  2 

Порождающая матрица G:
[[1 1 1]]
Проверочная матрица H:
[[1 1]
 [1 0]
 [0 1]]
Таблица синдромов:  {'[1 1]': [0], '[1 0]': [1], '[0 1]': [2]}

Исходное слово:  [1]
Отправленное слово:  [1 1 1]
Слово с 1 ошибками:  [1 1 0]
Синдром:  [0 1]
Исправленное слово:  [1 1 1]
Проверка исправленного слова с использованием матрицы H:  [0 0] 


Исходное слово:  [1]
Отправленное слово:  [1 1 1]
Слово с 2 ошибками:  [0 1 0]
Синдром:  [1 0]
Исправленное слово:  [0 0 0]
Проверка исправленного слова с использованием матрицы H:  [0 0] 


Исходное слово:  [1]
Отправленное слово:  [1 1 1]
Слово с 3 ошибками:  [0 0 0]
Синдром:  [0 0]
Синдром отсутствует в таблице синдромов.
Исправленное слово:  [0 0 0]
Проверка исправленного слова с использованием матрицы H:  [0 0] 



                                    Параметр r =  3 

Порождающая матрица G:
[[1

3.3 Функция формирования порождающей и проверочной
матриц расширенного кода Хэмминга 


In [29]:
def generate_extended_hamming_matrices(r):
    G, H = generate_hamming_matrices(r)
    H = np.vstack([H, np.zeros(len(H.T), dtype=int)])
    H = np.hstack([H, np.ones((len(H), 1), dtype=int)])
    G = np.hstack([G, np.zeros((len(G), 1), dtype=int)])
    for i in range(len(G)):
        if sum(G[i]) % 2 == 1:
            G[i, -1] = 1  # Устанавливаем последний элемент в 1, если сумма строки нечётная
    return G, H

3.4. Исследование расширенного кода Хэмминга 

In [30]:
def extended_hamming_code():
    print("\n\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>", "Для расширенного кода Хэмминга", "<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<")
    for r in range(2, 5):
        print("\n\n                                    Параметр r = ", r, '\n')
        G, H = generate_extended_hamming_matrices(r)
        syndrome_table = create_syndrome_table(H)
        print("Порождающая матрица G:", G, sep='\n')
        print("Проверочная матрица H:", H, sep='\n')
        print("Таблица синдромов: ", syndrome_table)
        check_errors_in_hamming_code(G, H, syndrome_table, r, extended=True)

In [31]:
extended_hamming_code()



>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> Для расширенного кода Хэмминга <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<


                                    Параметр r =  2 

Порождающая матрица G:
[[1 1 1 1]]
Проверочная матрица H:
[[1 1 1]
 [1 0 1]
 [0 1 1]
 [0 0 1]]
Таблица синдромов:  {'[1 1 1]': [0], '[1 0 1]': [1], '[0 1 1]': [2], '[0 0 1]': [3]}

Исходное слово:  [1]
Отправленное слово:  [1 1 1 1]
Слово с 1 ошибками:  [1 1 1 0]
Синдром:  [0 0 1]
Исправленное слово:  [1 1 1 1]
Проверка исправленного слова с использованием матрицы H:  [0 0 0] 


Исходное слово:  [1]
Отправленное слово:  [1 1 1 1]
Слово с 2 ошибками:  [1 0 1 0]
Синдром:  [1 0 0]
Синдром отсутствует в таблице синдромов.
Исправленное слово:  [1 0 1 0]
Проверка исправленного слова с использованием матрицы H:  [1 0 0] 


Исходное слово:  [1]
Отправленное слово:  [1 1 1 1]
Слово с 3 ошибками:  [0 1 0 0]
Синдром:  [1 0 1]
Исправленное слово:  [0 0 0 0]
Проверка исправленного слова с использованием матрицы H:  [0 0 0] 


Исходное сло